apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: webserver
spec:
  volumes:
    - name: logvol
      persistentVolumeClaim:
        claimName: logclaim
  containers:
    - image: nginx:alpine
      name: nginx-cont
      volumeMounts:
        - name: logvol
          mountPath: /var/www/nginx
