apiVersion: v1
kind: PersistentVolume
metadata:
  name: logvol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/volume/nginx
