apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logclaim
  namespace: default
spec:
  storageClassName: manual
  volumeName: logvol
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
