apiVersion: v1
kind: Pod
metadata:
  name: sleeping-pod
spec:
  securityContext:
    runAsUser: 1000
  volumes:
    - name: my-configmap-volume
      configMap:
       name: team-info
  containers:
  - image: busybox
    name: sleeping-cont
    securityContext:
      runAsUser: 2000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
    volumeMounts:
      - name: my-configmap-volume
        mountPath: /etc/my_team/
    command:
      - sleep
      - "3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always

