apiVersion: v1
kind: Pod
metadata:
  name: sleeping-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: busybox
    name: sleeping-cont
    securityContext:
      runAsUser: 2000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
    command:
      - sleep
      - "3600"
    envFrom:
      - configMapRef:
          name: team-info
  dnsPolicy: ClusterFirst
  restartPolicy: Always
