apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stressed
  name: stress-pod
spec:
  containers:
  - image: polinux/stress
    name: stress-cont
    # Resources have limits and requests
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "800Mi"
    # The command that the container inside this Pod
    # will run to stress it out
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "975M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
