apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: log
  name: fluent-pod
spec:
  containers:
  - image: fluent/fluentd
    name: fluent-cont
    resources: {}
    ports:
      - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
