apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    type: webserver
  name: nginx-clusterip-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: webserver
  type: ClusterIP
status:
  loadBalancer: {}

