apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: sleeping-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: sleeping
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 15
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: debian
            name: sleeping-container
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}

