apiVersion: v1
kind: Pod
metadata:
  name: sleeping-pod
spec:
  securityContext:
    runAsUser: 1000
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-secret-password
  containers:
  - image: busybox
    name: busy
    securityContext:
      runAsUser: 2000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: my-secret-volume
        mountPath: /my_secret_password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
